[package]
name = "kong-log-server"
version = "0.1.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.2.0"
serde_json = "1.0.39"
